// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore PrismaClient is generated by Prisma after `prisma generate`
import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as {
  prisma?: PrismaClient;
};

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: process.env.NODE_ENV === "development" ? ["error", "warn"] : ["error"],
    // For serverless environments, ensure proper connection handling
    datasources: {
      db: {
        url: process.env.DATABASE_URL,
      },
    },
  });

// In serverless environments, we don't want to reuse the client across invocations
// But we still need to prevent multiple instances in the same execution context
if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma;
}
